# Generated by Django 4.1 on 2022-08-06 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
